# Generated by Django 5.1.3 on 2024-12-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorauthuser',
            name='projects_done',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorauthuser',
            name='role',
            field=models.CharField(choices=[('Investor', 'Investor'), ('Developer', 'Developer'), ('Dual', 'Dual')], default='Investor', max_length=10),
        ),
        migrations.AddField(
            model_name='investorauthuser',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='investorauthuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investorauthuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investorauthuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='investorauthuser',
            name='ready_to_invest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='investorauthuser',
            name='return_goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
