# Generated by Django 5.1.3 on 2025-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_app', '0003_alter_investorauthuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorauthuser',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Select Role'), ('Investor', 'Investor'), ('Developer', 'Developer'), ('Dual', 'Dual')], default='', max_length=10, null=True),
        ),
    ]
